#!/usr/bin/env python3
"""
Script to generate expanded phrases for ranged weapons
"""

# Firearm failure phrases (need 140 more to reach 150)
firearm_failure = [
    "${targetName} anticipates the shot and dodges!",
    "The shot flies just wide!",
    "${attackerName} misjudges the distance!",
    "The shot veers off course!",
    "${targetName} sidesteps the blast!",
    "${attackerName}'s aim wavers slightly!",
    "The shot passes harmlessly by!",
    "${targetName} reads the shot and moves!",
    "${attackerName}'s sight picture wavers!",
    "The shot misses by inches!",
    "${targetName} shifts at the crucial moment!",
    "${attackerName} pulls the trigger too hard!",
    "The shot flies high!",
    "${targetName} ducks the shot!",
    "${attackerName}'s aim drifts!",
    "The shot skims past ${targetName}!",
    "${targetName} evades with practiced ease!",
    "${attackerName}'s timing is off!",
    "The shot goes wide right!",
    "${targetName} sees the muzzle flash and moves!",
    "${attackerName} anticipates the recoil wrong!",
    "The shot curves away!",
    "${targetName} pivots clear!",
    "${attackerName}'s breathing disrupts the shot!",
    "The shot fails to find ${targetName}!",
    "${targetName} weaves past the shot!",
    "${attackerName}'s grip shifts!",
    "The shot goes wide left!",
    "${targetName} moves at the last second!",
    "${attackerName} jerks the trigger!",
    "The shot misses due to poor aim!",
    "${targetName} proves too quick!",
    "${attackerName}'s follow-through is poor!",
    "The shot doesn't find its mark!",
    "${targetName} evades smoothly!",
    "${attackerName}'s stance wavers!",
    "The shot whistles past!",
    "${targetName} anticipates and dodges!",
    "${attackerName}'s sight alignment is off!",
    "The shot misses the target!",
    "${targetName} reads the trajectory!",
    "${attackerName} overcorrects!",
    "The shot fails to connect!",
    "${targetName} shifts weight and dodges!",
    "${attackerName}'s trigger squeeze isn't smooth!",
    "The shot passes ${targetName} harmlessly!",
    "${targetName} moves out of the way!",
    "${attackerName}'s aim point is just off!",
    "The shot misses by a narrow margin!",
    "${targetName} evades the incoming shot!",
    "${attackerName}'s trajectory is off!",
    "The shot goes astray by inches!",
    "${targetName} ducks at the right moment!",
    "${attackerName} flinches!",
    "The shot misses due to recoil!",
    "${targetName} sidesteps smoothly!",
    "${attackerName} rushes the shot!",
    "The shot fails to hit ${targetName}!",
    "${targetName} evades the shot!",
    "${attackerName}'s aim is imperfect!",
    "The shot sails past!",
    "${targetName} dodges the blast!",
    "${attackerName} misjudges the lead!",
    "The shot goes wide!",
    "${targetName} moves clear!",
    "${attackerName}'s aim is slightly off!",
    "The shot misses!",
    "${targetName} evades!",
    "${attackerName} fires but ${targetName} shifts!",
    "The shot doesn't connect!",
    "${targetName} dodges nimbly!",
    "${attackerName}'s shot is off!",
    "The shot flies past!",
    "${targetName} moves aside!",
    "${attackerName} misses the mark!",
    "The shot goes astray!",
    "${targetName} avoids the shot!",
    "${attackerName}'s aim fails!",
    "The shot sails wide!",
    "${targetName} evades quickly!",
    "${attackerName} shoots wide!",
    "The shot doesn't hit!",
    "${targetName} dodges clear!",
    "${attackerName}'s aim is poor!",
    "The shot misses ${targetName}!",
    "${targetName} shifts and dodges!",
    "${attackerName} fires but misses!",
    "The shot goes past!",
    "${targetName} moves in time!",
    "${attackerName}'s shot fails!",
    "The shot doesn't find ${targetName}!",
    "${targetName} evades the blast!",
    "${attackerName} shoots astray!",
    "The shot flies wide!",
    "${targetName} dodges the shot!",
    "${attackerName}'s aim is off!",
    "The shot passes by!",
    "${targetName} moves clear of the shot!",
    "${attackerName} misses!",
    "The shot goes off course!",
    "${targetName} avoids it!",
    "${attackerName} fires but fails!",
    "The shot sails by!",
    "${targetName} shifts clear!",
    "${attackerName}'s aim fails!",
    "The shot doesn't connect!",
    "${targetName} dodges away!",
    "${attackerName} shoots wide!",
    "The shot misses its mark!",
    "${targetName} moves aside quickly!",
    "${attackerName} fires off target!",
    "The shot goes harmlessly past!",
    "${targetName} evades the incoming shot!",
    "${attackerName}'s aim wavers and misses!",
    "The shot flies past the target!",
    "${targetName} anticipates and moves!",
    "${attackerName} fires poorly!",
    "The shot goes wide of its mark!",
    "${targetName} sidesteps the blast!",
    "${attackerName} fires but ${targetName} evades!",
    "The shot streaks past!",
    "${targetName} dodges with ease!",
    "${attackerName}'s shot is imperfect!",
    "The shot doesn't reach ${targetName}!",
    "${targetName} moves out of range!",
    "${attackerName} shoots but the aim is poor!",
    "The shot misses cleanly!",
    "${targetName} shifts and avoids!",
    "${attackerName} pulls the shot!",
    "The gunfire misses!",
    "${targetName} evades the attack!",
    "${attackerName} fires with poor aim!",
    "The shot goes astray!",
    "${targetName} dodges the firearm!",
    "${attackerName}'s shot fails to land!",
    "The blast misses!"
]

# Firearm critical failure phrases (need 140 more to reach 150)
firearm_critical_failure = [
    "The powder fails to ignite!",
    "${attackerName}'s weapon jams hard!",
    "The hammer falls with no discharge!",
    "${attackerName} fumbles the reload!",
    "The firearm clicks uselessly!",
    "${attackerName}'s gun misfires badly!",
    "The powder charges wrong!",
    "${attackerName} nearly shoots themselves!",
    "The weapon fails catastrophically!",
    "${attackerName}'s firearm explodes slightly!",
    "The trigger mechanism breaks!",
    "${attackerName} fumbles and drops the gun!",
    "The firearm backfires!",
    "${attackerName}'s weapon jams completely!",
    "The shot fires into the ground!",
    "${attackerName} fumbles the trigger pull badly!",
    "The powder explodes prematurely!",
    "${attackerName}'s aim is catastrophically wrong!",
    "The weapon nearly explodes!",
    "${attackerName} loses grip on the firearm!",
    "The hammer snaps!",
    "${attackerName}'s gun fails spectacularly!",
    "The barrel clogs!",
    "${attackerName} fumbles disastrously!",
    "The weapon misfires into the sky!",
    "${attackerName}'s firearm betrays them!",
    "The firing mechanism jams!",
    "${attackerName} nearly hits an ally!",
    "The gunpowder fizzles!",
    "${attackerName}'s weapon fails utterly!",
    "The shot goes backward somehow!",
    "${attackerName} fumbles the entire sequence!",
    "The firearm refuses to fire!",
    "${attackerName}'s trigger pull is catastrophic!",
    "The weapon explodes in hand!",
    "${attackerName} drops the firearm!",
    "The powder is damp!",
    "${attackerName}'s gun jams irreparably!",
    "The firing pin breaks!",
    "${attackerName} fumbles terribly!",
    "The weapon backfires loudly!",
    "${attackerName}'s firearm seizes!",
    "The hammer falls wrong!",
    "${attackerName} nearly injures themselves!",
    "The weapon fails completely!",
    "${attackerName}'s gun misfires!",
    "The barrel cracks!",
    "${attackerName} fumbles the shot!",
    "The firearm betrays ${attackerName}!",
    "${attackerName}'s aim couldn't be worse!",
    "The weapon jams solid!",
    "${attackerName} loses all control!",
    "The powder doesn't ignite!",
    "${attackerName}'s gun fails!",
    "The trigger doesn't work!",
    "${attackerName} fumbles badly!",
    "The firearm misfires!",
    "${attackerName}'s weapon explodes!",
    "The hammer doesn't strike!",
    "${attackerName} nearly shoots their foot!",
    "The gun refuses to fire!",
    "${attackerName}'s firearm jams!",
    "The powder charge fails!",
    "${attackerName} fumbles!",
    "The weapon malfunctions!",
    "${attackerName}'s shot is terrible!",
    "The gun clicks empty!",
    "${attackerName} loses the weapon!",
    "The firearm fails!",
    "${attackerName}'s trigger breaks!",
    "The weapon seizes!",
    "${attackerName} fumbles the gun!",
    "The shot misfires!",
    "${attackerName}'s aim fails!",
    "The firearm betrays!",
    "${attackerName} drops it!",
    "The gun jams!",
    "${attackerName}'s weapon fails!",
    "The hammer slips!",
    "${attackerName} fumbles!",
    "The firearm explodes!",
    "${attackerName}'s shot fails!",
    "The trigger jams!",
    "${attackerName} nearly injures an ally!",
    "The weapon misfires badly!",
    "${attackerName}'s gun seizes!",
    "The powder explodes wrong!",
    "${attackerName} fumbles the firearm!",
    "The shot goes wild!",
    "${attackerName}'s weapon breaks!",
    "The firing mechanism fails!",
    "${attackerName} loses grip!",
    "The firearm backfires!",
    "${attackerName}'s gun jams hard!",
    "The barrel splits!",
    "${attackerName} fumbles terribly!",
    "The weapon fails!",
    "${attackerName}'s shot is catastrophic!",
    "The gun refuses to work!",
    "${attackerName} drops the weapon!",
    "The firearm seizes!",
    "${attackerName}'s trigger fails!",
    "The hammer breaks!",
    "${attackerName} fumbles!",
    "The weapon explodes!",
    "${attackerName}'s aim is awful!",
    "The gun fails!",
    "${attackerName} nearly shoots backwards!",
    "The firearm jams!",
    "${attackerName}'s weapon misfires!",
    "The shot fails!",
    "${attackerName} loses control!",
    "The gun betrays!",
    "${attackerName}'s firearm breaks!",
    "The trigger snaps!",
    "${attackerName} fumbles badly!",
    "The weapon fails utterly!",
    "${attackerName}'s shot goes nowhere!",
    "The gun explodes!",
    "${attackerName} nearly injures themselves badly!",
    "The firearm fails catastrophically!",
    "${attackerName}'s weapon refuses!",
    "The powder fails!",
    "${attackerName} fumbles everything!",
    "The gun jams completely!",
    "${attackerName}'s shot is disastrous!",
    "The firearm betrays utterly!",
    "${attackerName} drops everything!",
    "The weapon seizes hard!",
    "${attackerName}'s aim is hopeless!",
    "The gun misfires spectacularly!",
    "${attackerName} fumbles!",
    "The firearm fails!",
    "${attackerName}'s trigger completely fails!",
    "The weapon explodes dangerously!",
    "${attackerName} loses the firearm!",
    "The gun refuses to fire!",
    "${attackerName}'s shot is terrible!"
]

# Print the lists for manual insertion
print("=== FIREARM FAILURE ADDITIONS ===")
for phrase in firearm_failure:
    print(f'    "{phrase}",')

print("\n=== FIREARM CRITICAL FAILURE ADDITIONS ===")
for phrase in firearm_critical_failure:
    print(f'    "{phrase}",')
